
-------------------作废
--menglei
--2018/08/30
--goodscategoryexcel CRM商品分类
  UPDATE TP_C_SQLINFO s
 set s.sql_info = 'SELECT G.CATEGORY_ID CATEGORYID, (SELECT B.BRANCH_NAME FROM TB_C_BRANCH B WHERE G.BRANCH_ID = B.BRANCH_ID) BRANCHID, DECODE(G.CHARGE_ROOM, 1, ''是'', 0, ''否'') CHARGEROOM, (SELECT P.PARAM_NAME FROM TP_C_SYSPARAM P WHERE G.SUPER_CATEGORY = P.CONTENT AND P.PARAM_TYPE = ''SUPERCATEGORY'') SUPERCATEGORY, G.CATEGORY_NAME CATEGORYNAME, (SELECT S.STAFF_NAME FROM TB_C_STAFF S WHERE G.RECORD_USER = S.STAFF_ID) RECORDUSER, TO_CHAR(G.RECORD_TIME, ''yyyy/MM/dd'') RECORDTIME, DECODE(G.STATUS, 1, ''有效'', 0, ''已删除'') STATUS, NVL(G.REMARK, '' '') REMARK, (SELECT B.BRANCH_NAME FROM TB_C_BRANCH B WHERE B.BRANCH_ID = G.BRANCH_ID AND B.BRANCH_NAME LIKE ''%'' || :PRICEBRANCHNAME || ''%'') BRANCHNAME, (SELECT SY.PARAM_NAME FROM TP_C_SYSPARAM SY WHERE SY.CONTENT = G.SUPER_CATEGORY AND SY.PARAM_TYPE = ''SUPERCATEGORY'' AND S.PARAM_NAME LIKE ''%'' || :SUPERCATEGORY || ''%'') PARAMNAME FROM TP_C_GOODSCATEGORY G AND G.CATEGORY_NAME LIKE ''%'' || :CATEGORYNAME || ''%'' AND G.CHARGE_ROOM LIKE ''%'' || :CHARGEROOM || ''%'' AND G.STATUS LIKE ''%'' || :CATEGORYSTATUS || ''%'' AND (G.BRANCH_ID LIKE DECODE($BRANCHID, ''100001'', ''%'', $BRANCHID) OR G.BRANCH_ID LIKE DECODE($BRANCHID, (SELECT C.BRANCH_ID FROM TB_C_BRANCH C WHERE C.RANK = ''0''), ''%'', $BRANCHID)) ORDER BY CATEGORYID DESC '
 where s.sql_name = 'goodscategoryexcel';
 commit;




